version: "3.9"
services:
app:
build: .
image: aspm-demo:latest
ports:
- "3000:3000"
environment:
- NODE_ENV=development
volumes:
- ./data:/app/data # デモ用（Path Traversal の範囲はコンテナ内に限定）
restart: unless-stopped

